M48
; DRILL file {KiCad (6.0.0)} date Wed Mar 30 15:51:51 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-30T15:51:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X3.4689Y-2.4694
T2
X2.8445Y-2.7963
X2.8445Y-2.9931
T0
M30
